http://scipy-lectures.org

In [1]:
import sklearn

In [6]:
from sklearn import preprocessing
import numpy as np

In [12]:
data = np.array([[1,-1.,2], [0,0,1],[2,1,-1]])
data

array([[ 1., -1.,  2.],
       [ 0.,  0.,  1.],
       [ 2.,  1., -1.]])

In [14]:
data_x = preprocessing.scale(data)
data_x

array([[ 0.        , -1.22474487,  1.06904497],
       [-1.22474487,  0.        ,  0.26726124],
       [ 1.22474487,  1.22474487, -1.33630621]])

In [16]:
# 零均值
data_x.mean(axis=0)

array([0.00000000e+00, 0.00000000e+00, 1.48029737e-16])

In [19]:
# 标准方差
data_x.std(axis=0)

array([1., 1., 1.])

In [20]:
binary = preprocessing.Binarizer().fit(data)
binary

Binarizer(copy=True, threshold=0.0)

In [21]:
binary.transform(data)

array([[1., 0., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

In [22]:
preprocessing.Binarizer(threshold=1.1).fit(data).transform(data)

array([[0., 0., 1.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [27]:
m = preprocessing.Normalizer().fit(data)
mm = m.transform(data)

In [28]:
np.linalg.norm(mm, axis=1)

array([1., 1., 1.])

In [29]:
en = preprocessing.OneHotEncoder()
en

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [41]:
x = np.arange(6)

In [48]:
x.shape = (3,2)
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [49]:
poly = preprocessing.PolynomialFeatures(degree=2, interaction_only=True)

In [51]:
poly.fit_transform(x)

array([[ 1.,  0.,  1.,  0.],
       [ 1.,  2.,  3.,  6.],
       [ 1.,  4.,  5., 20.]])

In [52]:
from sklearn.datasets import load_iris

In [53]:
iris = load_iris()

In [55]:
from sklearn.svm import SVC

In [68]:
svm_model = SVC().fit(X=iris["data"], y=iris["target"])

/Users/kean_qi/miniconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [69]:
svm_model

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [70]:
from sklearn.tree import DecisionTreeClassifier

聚类

In [71]:
from sklearn.cluster import KMeans

In [72]:
from sklearn import metrics

```
metrics.f1_score
metrics.auc
metrics.hamming_loss
```